### ISSUE TITLE
ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by ghost** [ArchiveCrew/blueblue#1]
When running this python script on a rpi3 B with python 2.7 installed i get this trace back.
Sometimes it will work just once when useing this cammand "python blueblue.py -f1.gif" But will fail with traceback when it attempts to do it a 2nd time. How would I resolve this issue?

[!] Exception in main() function
<type 'exceptions.AttributeError'>
("'int' object has no attribute 'strip'",)
'int' object has no attribute 'strip'
[!] Exception in main() function
<type 'exceptions.ValueError'>
('need more than 1 value to unpack',)
need more than 1 value to unpack
Traceback (most recent call last):
  File "blueblue.py", line 239, in <module>
    main()
  File "blueblue.py", line 233, in main
    x, y = inst          # __getitem__ allows args to be unpacked directly
ValueError: need more than 1 value to unpack

**Comment by ghost** [comment]
Ok found out why it did this. 
1. if any A2DP devices are in discovery mode it will crash this script.
2. any ascii names or Emojis as the BT name will crash this script. 
This is closed.
